spring:
  application:
    name: service-feign
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: 39.105.203.213
    port: 5672
    username: root
    password: root
management:
  endpoint:
    web:
      exposure:
        include: bus-refresh
server:
  port: 8765
feign:
  hystrix:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
foo: version3